spring.application.name=beans-to-boot
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.password=secret
spring.datasource.username=myuser
spring.threads.virtual.enabled=true
spring.sql.init.mode=always